#pragma once
#include <SDL.h>
#include "graphics/color.h"
#include "graphics/gfxdevice.h"
#include "platform/app.h"
#include "platform/common.h"
#include "platform/debug.h"
#include "platform/input.h"
#include "math/matrix.h"
#include "math/vector2.h"
#include "math/vector3.h"
#include "math/point.h"
